services:
  mysql:
    image: 'mysql:8.1'
    environment:
      - 'MYSQL_DATABASE=hrm'
      - 'MYSQL_PASSWORD=mysqladmin'
      - 'MYSQL_ROOT_PASSWORD=very_secret'
      - 'MYSQL_USER=mysqladmin'
    ports:
      - '3306:3306'
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=rabbitmq_admin'
      - 'RABBITMQ_DEFAULT_USER=rabbitmq_admin'
    ports:
      - '5672:5672'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
