spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:10}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
  datasource:
    url: 'jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:hrm_stg}?useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true&useSSL=true&requireSSL=true'
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    driverClassName: com.mysql.cj.jdbc.Driver
  docker:
    compose:
      enabled: false
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: none
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:}
    password: ${RABBITMQ_PASSWORD:}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:local}
system:
  name:
    mail: HRM System - Staging
aws:
  s3:
    accessKeyId: ${AWS_ACCESS_KEY_ID:}
    secretAccessKey: ${AWS_SECRET_ACCESS_KEY:}
    region: ${AWS_REGION:ap-southeast-1}
    bucket: ${AWS_S3_BUCKET:hrm-tool-stg}
    object:
      url: 'https://${aws.s3.bucket}.s3.${aws.s3.region}.amazonaws.com/'
server:
  address: 0.0.0.0
  port: ${SERVER_PORT:8080}
hrm:
  app:
    jwtSecret: ${JWT_SECRET:}
    jwtExpiration: ${JWT_EXPIRATION:86400000}
    refreshTokenExpiration: ${REFRESH_TOKEN_EXPIRATION:86400000}
logging:
  level:
    com:
      vatek:
        hrmtoolnextgen: INFO
    root: WARN

