spring:
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis-service}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      database: ${SPRING_DATA_REDIS_DATABASE:10}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-service:3306/hrm?createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:mysqladmin}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  docker:
    compose:
      enabled: false
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: none
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq-service}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:rabbitmq_admin}
    password: ${SPRING_RABBITMQ_PASSWORD}
    virtual-host: ${SPRING_RABBITMQ_VIRTUAL_HOST:local}
server:
  address: 0.0.0.0
  port: ${SERVER_PORT:8081}
hrm:
  app:
    jwtSecret: ${HRM_APP_JWT_SECRET:change-me}
    jwtExpiration: ${HRM_APP_JWT_EXPIRATION:86400000}
    refreshTokenExpiration: ${HRM_APP_REFRESH_TOKEN_EXPIRATION:86400000}

