apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hrm-tool

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - mysql/statefulset.yaml
  - mysql/service.yaml
  - redis/deployment.yaml
  - redis/service.yaml
  - rabbitmq/statefulset.yaml
  - rabbitmq/service.yaml
  - app/deployment.yaml
  - app/service.yaml
  - ingress.yaml
  - hpa.yaml
  - network-policy.yaml
  - pod-disruption-budget.yaml
