apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hrm-app-pdb
  namespace: hrm-tool
  labels:
    app: hrm-app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: hrm-app

