apiVersion: v1
kind: Service
metadata:
  name: hrm-app-service
  namespace: hrm-tool
  labels:
    app: hrm-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: hrm-app

---
apiVersion: v1
kind: Service
metadata:
  name: hrm-app-service-nodeport
  namespace: hrm-tool
  labels:
    app: hrm-app
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
    nodePort: 30081
  selector:
    app: hrm-app

